name: todosobremiclub_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8

  # 🔹 Para abrir la app / web de Instagram
  url_launcher: ^6.2.1

  # 🔹 Formato de moneda ARS ($ 10.000,00)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo-tsmc.png
    - assets/icons/instagram.png
