// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpujg0SEZFpzL2h8vAZ71MifV3zWoyoNw',
    appId: '1:1002352386101:web:f04f018ed8476bf7dbd17c',
    messagingSenderId: '1002352386101',
    projectId: 'todosobremiclub-5e5a4',
    authDomain: 'todosobremiclub-5e5a4.firebaseapp.com',
    storageBucket: 'todosobremiclub-5e5a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxwqkmPhT4ehVRVumz6lT6C89mheUfUKQ',
    appId: '1:1002352386101:android:cc0bd0f3531b1138dbd17c',
    messagingSenderId: '1002352386101',
    projectId: 'todosobremiclub-5e5a4',
    storageBucket: 'todosobremiclub-5e5a4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbLvG78ClBSI60ZT4Tk0oqFuUbqGjtPA',
    appId: '1:1002352386101:ios:02929ff3b46a89e5dbd17c',
    messagingSenderId: '1002352386101',
    projectId: 'todosobremiclub-5e5a4',
    storageBucket: 'todosobremiclub-5e5a4.firebasestorage.app',
    iosBundleId: 'com.example.todosobremiclubApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbLvG78ClBSI60ZT4Tk0oqFuUbqGjtPA',
    appId: '1:1002352386101:ios:02929ff3b46a89e5dbd17c',
    messagingSenderId: '1002352386101',
    projectId: 'todosobremiclub-5e5a4',
    storageBucket: 'todosobremiclub-5e5a4.firebasestorage.app',
    iosBundleId: 'com.example.todosobremiclubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpujg0SEZFpzL2h8vAZ71MifV3zWoyoNw',
    appId: '1:1002352386101:web:4062cbbb4c15ee41dbd17c',
    messagingSenderId: '1002352386101',
    projectId: 'todosobremiclub-5e5a4',
    authDomain: 'todosobremiclub-5e5a4.firebaseapp.com',
    storageBucket: 'todosobremiclub-5e5a4.firebasestorage.app',
  );
}
